#!/usr/bin/env bash
# =============================================================================
# Generate Ansible Inventory from Terraform Outputs
# =============================================================================
# This script automatically creates an Ansible inventory file from your
# Terraform outputs, so you don't have to manually edit hosts.ini
#
# Usage:
#   ./generate-inventory.sh
#   ./generate-inventory.sh /path/to/terraform/directory
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Default terraform directory (relative to script)
TERRAFORM_DIR="${1:-../terraform}"
INVENTORY_FILE="./inventory/hosts.ini"
SSH_KEY_PATH="${HOME}/.ssh/k8s-cluster-key.pem"  # Update this to your key path

log_info "Generating Ansible inventory from Terraform..."

# Check if terraform directory exists
if [ ! -d "$TERRAFORM_DIR" ]; then
    log_error "Terraform directory not found: $TERRAFORM_DIR"
    exit 1
fi

# Change to terraform directory
cd "$TERRAFORM_DIR"

# Check if terraform is initialized
if [ ! -d ".terraform" ]; then
    log_error "Terraform not initialized. Run 'terraform init' first."
    exit 1
fi

log_info "Fetching Terraform outputs..."

# Get master IPs
MASTER_PUBLIC_IPS=$(terraform output -json master_public_ips 2>/dev/null | jq -r '.[]')
MASTER_PRIVATE_IPS=$(terraform output -json master_private_ips 2>/dev/null | jq -r '.[]')

# Get worker IPs
WORKER_PUBLIC_IPS=$(terraform output -json worker_public_ips 2>/dev/null | jq -r '.[]')
WORKER_PRIVATE_IPS=$(terraform output -json worker_private_ips 2>/dev/null | jq -r '.[]')

# Get Load Balancer DNS
LB_DNS=$(terraform output -raw load_balancer_dns 2>/dev/null || echo "UNKNOWN")

# Get S3 bucket name
S3_BUCKET=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "UNKNOWN")

# Check if we got the outputs
if [ -z "$MASTER_PUBLIC_IPS" ]; then
    log_error "Could not fetch Terraform outputs. Make sure you've run 'terraform apply' successfully."
    exit 1
fi

# Go back to ansible directory
cd - > /dev/null

# Create inventory directory if it doesn't exist
mkdir -p inventory

log_info "Creating inventory file: $INVENTORY_FILE"

# Generate inventory file
cat > "$INVENTORY_FILE" << 'EOF'
# =============================================================================
# Ansible Inventory - Auto-generated from Terraform
# =============================================================================
# Generated on: DATE_PLACEHOLDER
# 
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate with: ./generate-inventory.sh
# =============================================================================

[masters]
EOF

# Add masters
MASTER_PUBLIC_ARRAY=($MASTER_PUBLIC_IPS)
MASTER_PRIVATE_ARRAY=($MASTER_PRIVATE_IPS)

for i in "${!MASTER_PUBLIC_ARRAY[@]}"; do
    MASTER_NUM=$((i + 1))
    MASTER_NAME=$(printf "master%02d" $MASTER_NUM)
    IS_LEADER="false"
    [ $i -eq 0 ] && IS_LEADER="true"
    
    echo "${MASTER_NAME} ansible_host=${MASTER_PUBLIC_ARRAY[$i]} private_ip=${MASTER_PRIVATE_ARRAY[$i]} is_leader=${IS_LEADER}" >> "$INVENTORY_FILE"
done

# Add workers
cat >> "$INVENTORY_FILE" << 'EOF'

[workers]
EOF

WORKER_PUBLIC_ARRAY=($WORKER_PUBLIC_IPS)
WORKER_PRIVATE_ARRAY=($WORKER_PRIVATE_IPS)

for i in "${!WORKER_PUBLIC_ARRAY[@]}"; do
    WORKER_NUM=$((i + 1))
    WORKER_NAME=$(printf "worker%02d" $WORKER_NUM)
    
    echo "${WORKER_NAME} ansible_host=${WORKER_PUBLIC_ARRAY[$i]} private_ip=${WORKER_PRIVATE_ARRAY[$i]}" >> "$INVENTORY_FILE"
done

# Add group variables
cat >> "$INVENTORY_FILE" << EOF

[k8s_cluster:children]
masters
workers

[k8s_cluster:vars]
# SSH Configuration
ansible_user=ubuntu
ansible_ssh_private_key_file=${SSH_KEY_PATH}
ansible_python_interpreter=/usr/bin/python3
EOF

# Replace date placeholder
sed -i "s/DATE_PLACEHOLDER/$(date '+%Y-%m-%d %H:%M:%S')/" "$INVENTORY_FILE"

log_info "Inventory file created successfully!"

# Update group_vars/all.yml with LB DNS and S3 bucket
log_info "Updating group_vars/all.yml with Terraform outputs..."

if [ -f "inventory/group_vars/all.yml" ]; then
    # Update load_balancer_dns
    if [ "$LB_DNS" != "UNKNOWN" ]; then
        sed -i "s|^load_balancer_dns:.*|load_balancer_dns: \"${LB_DNS}\"|" inventory/group_vars/all.yml
        log_info "  ✓ Updated load_balancer_dns: ${LB_DNS}"
    fi
    
    # Update s3_bucket_name
    if [ "$S3_BUCKET" != "UNKNOWN" ]; then
        sed -i "s|^s3_bucket_name:.*|s3_bucket_name: \"${S3_BUCKET}\"|" inventory/group_vars/all.yml
        log_info "  ✓ Updated s3_bucket_name: ${S3_BUCKET}"
    fi

    # ADD THIS BLOCK — copy-paste exactly after the s3_bucket_name part
    if [ "$LB_DNS" != "UNKNOWN" ]; then
        sed -i "s|^control_plane_endpoint:.*|control_plane_endpoint: \"${LB_DNS}:6443\"|" inventory/group_vars/all.yml 2>/dev/null || \
        log_info "  Updated control_plane_endpoint: ${LB_DNS}:6443"
    fi
fi

# Display summary
echo ""
log_info "========================================="
log_info "Inventory Summary"
log_info "========================================="
log_info "Masters: ${#MASTER_PUBLIC_ARRAY[@]}"
for i in "${!MASTER_PUBLIC_ARRAY[@]}"; do
    MASTER_NUM=$((i + 1))
    log_info "  master$(printf "%02d" $MASTER_NUM): ${MASTER_PUBLIC_ARRAY[$i]} (${MASTER_PRIVATE_ARRAY[$i]})"
done

echo ""
log_info "Workers: ${#WORKER_PUBLIC_ARRAY[@]}"
for i in "${!WORKER_PUBLIC_ARRAY[@]}"; do
    WORKER_NUM=$((i + 1))
    log_info "  worker$(printf "%02d" $WORKER_NUM): ${WORKER_PUBLIC_ARRAY[$i]} (${WORKER_PRIVATE_ARRAY[$i]})"
done

echo ""
log_info "Load Balancer: ${LB_DNS}"
log_info "S3 Bucket: ${S3_BUCKET}"
log_info "========================================="

# Test connectivity
echo ""
log_info "Testing SSH connectivity..."
if ansible all -m ping > /dev/null 2>&1; then
    log_info "✓ SSH connectivity test PASSED!"
    log_info ""
    log_info "You're ready to deploy! Run:"
    log_info "  ansible-playbook playbooks/site.yml"
else
    log_warn "✗ SSH connectivity test FAILED"
    log_warn "Please check:"
    log_warn "  1. SSH key path: ${SSH_KEY_PATH}"
    log_warn "  2. Security groups allow SSH from your IP"
    log_warn "  3. Instances are running"
    log_warn ""
    log_warn "Test manually with:"
    log_warn "  ansible all -m ping"
fi